name: awesome_flutter_extensions
description: Awesome flutter extensions to remove boilerplate
version: 0.0.1+1
homepage: https://bestofcode.dev
repository: https://github.com/nank1ro/awesome_flutter_extensions

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.3.0

flutter: null
